version: 2.1
executors:
  java:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
jobs:
  build:
    executor: java
    resource_class: xlarge
    steps:
      - run:
          environment:
            DEBIAN_FRONTEND: noninteractive
            _JAVA_OPTIONS: "-Xms2g -Xmx12g"
            GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=4"
          command: |
            sudo apt update
            sudo apt install -qy ca-certificates git
      - checkout
      - restore_cache:
          keys:
            - v3-gradle-cache
      - run:
          command: ./gradlew testAll --parallel --stacktrace
          no_output_timeout: 20m
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v3-gradle-cache
          when: on_success

